seed: 42
maxlen: 1024
tokenizer_run_name: gpt2
dataset_name: wikitext
dataset_config_name: wikitext-103-raw-v1

precision: bf16
multilang: False
multidevice: False
per_lang_embedding_layers: 0
ignore_token_id: -100

lr: 1e-4
lr_scheduler: cosine_warmup
d_model: 768
n_gqa_groups: 2
n_heads: 12
d_queries: 64
d_values: 64
q_bias: False
k_bias: False
v_bias: False
o_bias: False
d_inner: 4096
ffn_bias: True
attn_impl: gqa
infinite_attention_n_segments: 0
infinite_attention_update: False
n_decoder_layers: 12
dropout: 0.15
norm_type: layer
norm_eps: 0.00001
optimizer: adamw
weight_decay: 0.01
use_grok_scaled_attn: False
use_grokfast: ema
use_huginn: False
pre_self_attn_norm: False
post_self_attn_norm: True
pre_cross_attn_norm: False
post_cross_attn_norm: False
pre_ffn_norm: False
post_ffn_norm: True

grokfast_lambda: 2.0
grokfast_alpha: 0.98

ffn_type: phi3

moe_replace: False
moe_n_experts: 0
moe_top_k: 0
moe_diversity_loss_coefficient: 0.0
moe_diversity_inclusion: 0

millions_moe_n_heads: 0
millions_moe_d_keys: 0
millions_moe_dropout: 0.0

init_weights_from: normal
init_weights_gain: 0.2
init_weights_scale_residual: False
use_admin: False

positional_encoding_type: rotary
positional_encoding_dim: 64
learnable_positional_encoding: False

decoder_param_sharing_type: none
m_decoder_independent_layers: 0
activation_function: swiglu
heads_activation: none
embedding_compression_dim: 0
embedding_activation: none
embedding_scale: 1.0

batch_size: 8
batch_accumulation_steps: 192
warmup_steps: 8000
beta1: 0.9
beta2: 0.98
epsilon: 1.e-9
label_smoothing: 0.0
clip_grad_norm: 1.0

early_stop: False
early_stop_patience: 3
early_stop_min_delta: 0.0
early_stop_checkpoint_window: 3

distillation_teacher_run_name:

start_step: 0
print_frequency: 1600
print_examples: 
  - "The Higgs boson, sometimes called the Higgs particle, is"
  - "Johnson led his Australian team to England in 1956. The team"
print_example_tgts:
  - "The Higgs boson, sometimes called the Higgs particle, is an elementary particle in the Standard Model of particle physics produced by the quantum excitation of the Higgs field, one of the fields in particle physics theory."
  - "Johnson led his Australian team to England in 1956. The team's visit to England coincided with what was described by Wisden as \" the wettest of all summers in memory \"."
decoder_device: cuda:0
save_initial_checkpoint: False
cudnn_benchmark: False
detect_nans: False
debug: False

compile_model: False
dynamo_cache_size_limit: 16

bayesian_iter: False
