version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  python-server:
    build:
      context: ../../python/server
    ports:
      - 5000:5000
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: postgres:5432
      POSTGRES_USER: myuser
      POSTGRES_PW: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_SCHEMA: myschema
      SERVER_HOST_URL: 0.0.0.0
      SERVER_PORT: 5000
