tokenizer_run_name: BPE_SEPARATE

d_model: 768
n_heads: 10
d_inner: 3072
n_encoder_layers: 12
n_decoder_layers: 12
encoder_param_sharing_type: cycle-rev
decoder_param_sharing_type: cycle-rev
m_encoder_independent_layers: 6
m_decoder_independent_layers: 6

n_steps: 300000
