d_model: 512
n_gqa_groups: 1
n_heads: 8
d_queries: 64
d_values: 64
d_inner: 2048
use_moe: false
n_experts: 0
moe_top_k: 0
moe_diversity_loss_coefficient: 0.0
moe_diversity_inclusion_epoch: 0
n_encoder_layers: 6
n_decoder_layers: 6
dropout: 0.1

maxlen: 150

init_weights_from: glorot_uniform
init_weights_gain: 1.0
use_admin: false

positional_encoding_type: rotary
positional_encoding_dim: 64
learnable_positional_encoding: false

encoder_param_sharing_type: none
decoder_param_sharing_type: none
m_encoder_independent_layers: 0
m_decoder_independent_layers: 0
activation_function: relu

tokens_in_batch: 5000
target_tokens_per_batch: 25000
n_steps: 100000
warmup_steps: 8000
beta1: 0.9
beta2: 0.98
epsilon: 1.e-9
label_smoothing: 0.1
clip_grad_norm: 0.0

prune_mode: none
prune_type: all
prune_structured: false
prune_heads_amount: 0.0
prunt_heads_norm: 2
prune_ffn_amount: 0.0
prune_ffn_norm: 2
n_prune_retrains: 2
prune_retrain_n_steps: 10000
prune_retrain_warmup_steps: 800

distillation_teacher_run_name:

train_vae: false
latent_size: 512
latent_seq_len: 16
kl_loss_coefficient: 1.0
vae_tie_embeddings: false

start_epoch: 0
print_frequency: 20
device: cuda
save_initial_checkpoint: false
cudnn_benchmark: false
detect_nans: false

torch_compile_model: false
dynamo_cache_size_limit: 16

early_stopping: false
early_stopping_patience: 10
early_stopping_min_delta: 0.0
